#!/bin/sh


# ----------------------------------------------------------------------------
readonly SETUP=${0##*/}
readonly APPLICATION='sendsms'
readonly PREREQUISITES='bash sed curl'
# ----------------------------------------------------------------------------


# run as root -->
if [ "$USER" != 'root' ]; then
  [ "$LOGNAME" != 'root' ] && echo "Please run as root" && exit 1
fi
# run as root <--


# setup functions -->
setup_usage () {
  rc=0
  [ -n "${*}" ] && echo "${*}" && rc=1
  echo "\
Usage:
  $SETUP [install | uninstall]"

  exit $rc
}

setup_check_prerequisites () {
  for cmd in $PREREQUISITES; do
    command -v $cmd >/dev/null
    [ $? -ne 0 ] && echo "you need the '$cmd' command" && exit 1
  done
}

setup_install () {
  # application
  cp sendsms /usr/local/bin/sendsms
  chown root:root /usr/local/bin/sendsms
  chmod 0755 /usr/local/bin/sendsms
  # sed requirement
  mkdir -p /usr/local/share/sendsms
  cp urlencode.sed /usr/local/share/sendsms/urlencode.sed
  chown root:root /usr/local/share/sendsms/urlencode.sed
  chmod 0644 /usr/local/share/sendsms/urlencode.sed
  # bash completion
  if [ -d /usr/share/bash-completion/completions ]; then
    cp ac_sendsms /usr/share/bash-completion/completions/sendsms
    chown root:root /usr/share/bash-completion/completions/sendsms
    chmod 0644 /usr/share/bash-completion/completions/sendsms
  fi
}

setup_uninstall () {
  rm -f /usr/local/bin/sendsms
  rm -fr /usr/local/share/sendsms
  if [ -d /usr/share/bash-completion/completions ]; then
    rm -f /usr/share/bash-completion/completions/sendsms
  fi
}
# setup functions <--


# parse cli -->
case $1 in
  help) setup_usage ;;
  install)
    setup_check_prerequisites
    setup_install ;;
  uninstall) setup_uninstall ;;
  *) setup_usage 'invalid or missing argument' ;;
esac
# parse cli <--


exit 0
